project/compare_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),

    # url(r'^(?P<name>[0-9]+)/product_metadata$', views.product_metadata, name='product_metadata'),

    # url(r'^(?P<name>[0-9]+)/category/$', views.category, name='category'),
 
    # url(r'^(?P<name>[0-9]+)/sub_category/$', views.sub_category, name='sub_category'),
]

project/project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
 	url(r'', include('compare_app.urls')),
]

project/compare_app/models.py
# from django.db import models

# # Create your models here.


# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')


# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)


from django.db import models

# Create your models here.


class Product(models.Model):
	url = models.CharField(max_length=1000)
	site =models.CharField(
        max_length=10,
        choices=(('ebay','EBay'),('amazon','Amazon'),('snapdeal','Snapdeal'),('paytm','PayTM')),
        default='ebay',
        
    )
	active = models.BooleanField(default=True)


class Category(models.Model):
	name = models.CharField(max_length=100)


class SubCategory(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	# catagory_id = models.IntegerField(default=0)
	name = models.CharField(max_length=100)

class ProductMetadata(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	# product_id = models.IntegerField(default=0)
	sub_catagory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
	name = models.CharField(max_length=200)
	description = models.TextField("Description", null=True, blank=True)
	key_words = models.CharField(max_length=300)
	price =  models.FloatField(default=0)
	rating = models.DecimalField(max_digits=5, decimal_places=2)
	latest = models.BooleanField(default=True)



# from compare_app.models import Product




# catagorys
# name(string)
# sub catagorys
# catagory_id(int)
# name(string)
# Product Metadata
# product_id(int)
# sub_catagory_id(int)
# name(string)
# description(text)
# key words(string)
# price(integer)
# rating(integer)
# latest(boolean)

project/compare_app/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponse
from .models import Product,ProductMetadata

def index(request):
	# product = get_object_or_404(Product,pk=product_id)
	#return HttpResponse("Hello, You're looking at url and product_id %s." % (product.url))
	# results = []
	# try:
	# 	results = ProductMetadata.objects.filter(name__icontains=request.GET["Name"],latest=1)
	# except Exception as e:
	# 	print e
	return render(request, 'compare_app/index.html')

	# return render(request, 'compare_app/detail.html', {'product': product})
def search (request):
	results = []
	try:
		results = ProductMetadata.objects.filter(name__icontains=request.GET["search"],latest=1)
	except Exception as e:
		print e
	return render(request, 'compare_app/boot.html', {'results': results})

def product_metadata(request,name):
	results = ProductMetadata.objects.filter(name__icontains='iphone')
	#return HttpResponse("You're looking at product details %s." % (name))
	return render(request, 'compare_app/results.html', {'results': results})

def category(request, name):
	response = "You're looking at the category of the product %s."
	return HttpResponse(response % name)

def sub_category(request, name):
	return HttpResponse("You're looking at sub categories %s." % (name))

project/compare_app/templates/compare_app/boot.html
{% extends "compare_app/template.html" %}
{% block content %}
	<div class="row">
		<div class="jumbotron">
		<h1>Comparison Engine</h1>      
		<p  style="text-indent: 1em;">Search your product and know about it !</p>


		</div>  
	</div>
	<div class="container">
		<div class="row">

			{{name}}
			<form>
				<div class="input-group add-on">
			      <input class="form-control" placeholder="Search" name="search" id="srch-term" type="text">
			      <div class="input-group-btn">
			        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
			      </div>
			    </div>
			</form>
		</div>
		<div class="row">
		<table class="table table-hover table-bordered">
			<thead>
				<tr>
					<th class="col-md-3">Product</th>
					<th class="col-md-5">Description</th>
					<th class="col-md-2">Rating</th>
					<th class="col-md-2">Price</th>
				</tr>
			</thead>
			<tbody>
				{% for result in results %}
					<tr>
						<td class="col-md-3">{{ result.name }}</td>
						<td class="col-md-5">{{ result.description }}</td>
						<td class="col-md-2">{{ result.rating }}</td>
						<td class="col-md-2">{{ result.price}}</td>
					</tr>
				{% endfor %}
			</tbody>
			
		</table>
		</div>
	</div>
{% endblock %}

project/compare_app/templates/compare_app/detail.html
<h1>{{ product.url }}</h1>
<ul>
{% for product_metadatum in product.productmetadata_set.all %}
    <li>{{ product_metadatum.name }}</li>
    <li>{{ product_metadatum.price }}</li>
    <li>{{ product_metadatum.rating }}</li>
    <li>{{ product_metadatum.description }}</li>
{% endfor %}
</ul>

project/compare_app/templates/compare_app/index.html
{% extends "compare_app/template.html" %}
{% load static %}
{% block content %}
	
	<br>
	<MARQUEE WIDTH=1000 HEIGHT=100 BEHAVIOR=ALTERNATE>
	<h1><b>Welcome to Our Website !</b></h1>
	</MARQUEE>
	
	<h4>Everyday we use thousands of different products, from mobiles to televisions and air conditioners to washing machines. But have you ever  faced the difficulty of choosing the right product from our so called "E-Commerce" websites? </h4>
	<hr>
	
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
    <li data-target="#carousel-example-generic" data-slide-to="5"></li>
    
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src='{% static "images/paytm.png" %}' width= "100%" height=" 100px"  background-size=  "100%"/>
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
      <img src='{% static "images/snapdeal.png" %}'  />
      <div class="carousel-caption">
       
      </div>

    </div>
     <div class="item">
      <img src='{% static "images/amazon.png" %}'  />
      <div class="carousel-caption">
       
      </div>

    </div>
     <div class="item">
      <img src='{% static "images/ebay.png" %}'  />
      <div class="carousel-caption">
       
      </div>

    </div>
     <div class="item">
      <img src='{% static "images/amazon (1).png" %}'  />
      <div class="carousel-caption">
       
      </div>

    </div>
    
    
  </div>



  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock %}




 

project/compare_app/templates/compare_app/results.html
<ul>
	{% for result in results %}
		<li>{{ result.name }}</li>
	{% endfor %}
</ul>

project/compare_app/templates/compare_app/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
      /* Remove the navbar's default margin-bottom and rounded borders */ 
       
     
      .navbar {
      margin-top: 0px;
      margin-bottom: 0px;
      overflow: auto;
       }
    
      
      /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
      .row.content {height: 450px}
      
      /* Set gray background color and 100% height */
     
      
      /* Set black background color, white text and some padding */
      footer {
        background-color: #555;
        color: white;
        padding: 15px;
        position: absolute;
        right: 0;
        bottom: 0;
        left: 0;
      }
      
      /* On small screens, set height to 'auto' for sidenav and grid */

      * {box-sizing:border-box}
      body {
        font-family: Verdana,sans-serif;
        margin:0; 
        min-height: 100%;
      }

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .prev, .next,.text {font-size: 11px}
}
    </style>
  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
          </button>
          <a class="navbar-brand" href="#"><img src='{% static "images/sqe.gif"%}' height="30" width="50" /></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'search' %}">Product Search </a></li>
            <li><a href="#">Analytics</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/admin/login/?next=/admin/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
        </div>
      </div>
    </nav>
    

    <div class="container-fluid">
      {% block content %}{% endblock %}
    </div>
      

    <footer class="container-fluid text-center">
      <!-- <p>Footer Text</p> -->
    </footer>

  </body>
</html>